# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "84cb939e1a6eafc98769331078c35574"
application_url = "https://mobile-banner-app.fly.dev/"
embedded = true
name = "Mobile App banner"
handle = "mobile-app-banner-3"

[build]
dev_store_url = "gorgov-test-2023.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mobile-banner-app.fly.dev/auth/callback",
  "https://mobile-banner-app.fly.dev/auth/shopify/callback",
  "https://mobile-banner-app.fly.dev/api/auth/callback"
]

[pos]
embedded = false
